### ISSUE TITLE
functionalize all the prep stuff for the BT analysis

### ISSUE THREAD

**Issue by wcornwell** [latrodektus/UFC-Beard-Data#1]
We can make it all pretty and turn it into supplementary material at some point

**Comment by latrodektus** [comment]
Everything looks good dude. I only have two questions:
1) In model.other.outcomes, it looks like 164 observations are deleted due to missingness. Same for Model 3, 114 missing data. But nothing is missing that should cause this. I just want to make sure that the analysis is on the full data set.

2) I have to chat on how to report the Model1/2. I may just send you the written stuff and you can let me know what you think. I pretty much finished the whole thing.

**Comment by wcornwell** [comment]
Yup there was a :bug: in there.  Now fixed. No real changes to the results tho
