### ISSUE TITLE
Distribution/Frequency stats

### ISSUE THREAD

**Issue by latrodektus** [latrodektus/UFC-Beard-Data#4]
I would appreciate if the authors provided the distribution/frequencies statistics for each of the different facial hair categories, and how many fights between each category were in the dataset. In particular, how many fights were between bearded fighters vs. clean shaven/other fighters, which I would think is the most pertinent cell for the hypotheses.

**Comment by wcornwell** [comment]
facehair_winner | facehair_loser | Freq
-- | -- | --
clean-shaven | clean-shaven | 117
full beard | clean-shaven | 41
other facial hair | clean-shaven | 86
clean-shaven | full beard | 36
full beard | full beard | 23
other facial hair | full beard | 41
clean-shaven | other facial hair | 92
full beard | other facial hair | 34
other facial hair | other facial hair | 128

**Comment by wcornwell** [comment]
facehair_loser
facehair_winner     clean-shaven full beard other facial hair
  clean-shaven               117         36                92
  full beard                  41         23                34
  other facial hair           86         41               128

**Comment by wcornwell** [comment]
Very small changes since we figured out how not to lose a couple of fighters who didn't previously have a value for "previous fight"


facehair_winner | facehair_loser | Freq
-- | -- | --
clean-shaven | clean-shaven | 117
full beard | clean-shaven | 41
other facial hair | clean-shaven | 87
clean-shaven | full beard | 36
full beard | full beard | 23
other facial hair | full beard | 41
clean-shaven | other facial hair | 93
full beard | other facial hair | 34
other facial hair | other facial hair | 128
